
-- Drop existing tables if they exist to start fresh
DROP TABLE IF EXISTS rankings;
DROP TABLE IF EXISTS rounds;
DROP TABLE IF EXISTS drivers; -- We are removing this table entirely
DROP TABLE IF EXISTS series;

-- 1. Series Table: Stores the main events (Monthly, Zhuzhou, Rally, iRacing)
CREATE TABLE series (
    id TEXT PRIMARY KEY, -- e.g., 'monthly', 'zhuzhou'
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Rounds Table: Stores the time periods/stages for each series
CREATE TABLE rounds (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    series_id TEXT REFERENCES series(id) ON DELETE CASCADE,
    name TEXT NOT NULL, -- e.g., 'Round 1', 'Week 42'
    sequence INTEGER NOT NULL, -- To order rounds (1, 2, 3, 4)
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Rankings Table: Stores the performance AND driver info directly
-- This is denormalized as requested to simplify data updates (no separate drivers table)
CREATE TABLE rankings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id UUID REFERENCES rounds(id) ON DELETE CASCADE,
    driver_id TEXT NOT NULL, -- Storing the driver's display ID/Name directly (e.g., 'Sky Cheng')
    rank INTEGER NOT NULL,
    tier TEXT, -- 'S', 'A', 'B', etc.
    points INTEGER DEFAULT 0,
    safety_score INTEGER DEFAULT 0,
    podiums INTEGER DEFAULT 0,
    finished_races INTEGER DEFAULT 0,
    total_races INTEGER DEFAULT 0,
    display_races TEXT, -- For special formats like '43' in Rally or '38|42' pre-calculated
    trend TEXT DEFAULT 'STABLE', -- 'UP', 'DOWN', 'STABLE'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(round_id, driver_id) -- Ensure one entry per driver per round
);

-- Enable Row Level Security (RLS)
ALTER TABLE series ENABLE ROW LEVEL SECURITY;
ALTER TABLE rounds ENABLE ROW LEVEL SECURITY;
ALTER TABLE rankings ENABLE ROW LEVEL SECURITY;

-- Create policies to allow public read/write access (Simplified for development)
CREATE POLICY "Allow public read access on series" ON series FOR SELECT USING (true);
CREATE POLICY "Allow public insert on series" ON series FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on series" ON series FOR UPDATE USING (true);

CREATE POLICY "Allow public read access on rounds" ON rounds FOR SELECT USING (true);
CREATE POLICY "Allow public insert on rounds" ON rounds FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on rounds" ON rounds FOR UPDATE USING (true);

CREATE POLICY "Allow public read access on rankings" ON rankings FOR SELECT USING (true);
CREATE POLICY "Allow public insert on rankings" ON rankings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on rankings" ON rankings FOR UPDATE USING (true);

-- Insert Initial Series Data
INSERT INTO series (id, name) VALUES
('monthly', '月度锦标赛'),
('zhuzhou', '株洲速度节'),
('rally', '飞驰拉力赛'),
('iracing', 'iRacing League');

-- Insert Initial Rounds for Monthly Championship
INSERT INTO rounds (series_id, name, sequence) VALUES
('monthly', '第一轮：海选赛', 1),
('monthly', '第二轮：小组赛', 2),
('monthly', '第三轮：淘汰赛', 3),
('monthly', '第四轮：总决赛', 4);

-- Insert Initial Rounds for Zhuzhou Speed Festival
INSERT INTO rounds (series_id, name, sequence) VALUES
('zhuzhou', '株洲站：练习赛', 1),
('zhuzhou', '株洲站：排位赛', 2),
('zhuzhou', '株洲站：半决赛', 3),
('zhuzhou', '株洲站：冠军争夺赛', 4);

-- Insert Initial Rounds for Rally
INSERT INTO rounds (series_id, name, sequence) VALUES
('rally', '拉力赛：勘路', 1),
('rally', '拉力赛：夜间赛段', 2),
('rally', '拉力赛：长距离赛段', 3),
('rally', '拉力赛：超级赛段', 4);

-- Insert Initial Rounds for iRacing
INSERT INTO rounds (series_id, name, sequence) VALUES
('iracing', 'iRacing：季前热身', 1),
('iracing', 'iRacing：俱乐部杯', 2),
('iracing', 'iRacing：洲际对抗赛', 3),
('iracing', 'iRacing：赛季总决赛', 4);

-- Example Data Injection (Optional, you can run this manually in SQL editor if you want test data)
-- DO $$
-- DECLARE
--     r_id UUID;
-- BEGIN
--     SELECT id INTO r_id FROM rounds WHERE series_id = 'monthly' AND sequence = 4 LIMIT 1;
--     IF r_id IS NOT NULL THEN
--         INSERT INTO rankings (round_id, driver_id, rank, tier, points, safety_score, podiums, finished_races, total_races, trend)
--         VALUES 
--         (r_id, 'Sky Cheng', 1, 'S', 872, 12, 0, 42, 42, 'UP'),
--         (r_id, 'K. Sato', 2, 'S', 856, 14, 12, 41, 42, 'DOWN');
--     END IF;
-- END $$;
